version: 2
jobs:
  build:
    working_directory: ~/foodsaving-backend
    docker:
      - image: python:3.5.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install packages
          command: |
            set -x
            apt-get update -qq && apt-get install -y git docker
            /usr/local/bin/pip install virtualenv
            virtualenv --no-site-packages ~/env
            ~/env/bin/pip install docker-compose
      - run:
          name: clone other repos
          command: |
            set -x
            cd ~
            git clone https://github.com/yunity/foodsaving-docker
            mv foodsaving-backend foodsaving-docker/
            cd foodsaving-docker
            git clone https://github.com/yunity/foodsaving-frontend
      - run:
          name: compose
          command: |
            set -x
            cd ~/foodsaving-docker
            ~/env/bin/docker-compose up -d
      - run:
          name: Run backend tests
          command: docker-compose exec backend ./manage.py test




# machine:
#   python:
#     version: 3.5.3  # same as on production server
#   services:
#     - redis
# database:
#   override:
#     - cp config/local_settings.py.ci config/local_settings.py
# test:
#   override:
#     - coverage run manage.py test
#     - flake8 ./
#   post:
#     - coverage html -d $CIRCLE_ARTIFACTS
#     - pip install codecov && codecov
#     - if [ $CIRCLE_BRANCH ]; then bash trigger_e2e_build.sh; fi
# deployment:
#   dev:
#     branch: [master, production]
#     commands:
#       - ./deploy.sh
