# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 09:03
from __future__ import unicode_literals

from django.db import migrations
import django_enumfield.db.fields
import foodsaving.subscriptions.models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelsubscription',
            old_name='reply_channel',
            new_name='destination',
        ),
        migrations.AddField(
            model_name='channelsubscription',
            name='typus',
            field=django_enumfield.db.fields.EnumField(default=0, enum=foodsaving.subscriptions.models.SubscriptionTypus),
        ),
    ]
