# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20170820_0903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChannelSubscription',
            new_name='Subscription',
        ),
    ]
